# Generated by Django 2.2.3 on 2019-07-30 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(choices=[('ON', 'contact-status online'), ('BU', 'contact-status busy'), ('AW', 'contact-status away'), ('DF', 'contact-status')], default='DF', max_length=2)),
                ('src', models.URLField(default='https://www.kasandbox.org/programming-images/creatures/Hopper-Cool.png', max_length=250)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('preview', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]


