# Generated by Django 2.2.3 on 2019-07-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('S', 'sent'), ('R', 'recive')], max_length=1)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sss2', to='users.Contacts')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sss', to='users.Contacts')),
            ],
        ),
    ]
