# Generated by Django 2.2.3 on 2019-08-12 09:22

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=10)),
                ('birthday', models.DateField(null=True)),
                ('number_of_friends', models.IntegerField()),
            ],
        ),
    ]