# Generated by Django 2.2.3 on 2019-08-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='vnvkhjkn', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='hknn,', max_length=30),
            preserve_default=False,
        ),
    ]
