# Generated by Django 2.2.3 on 2019-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0002_auto_20190812_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
